source "https://rubygems.org"
ruby "3.3.6"

gem "mysql"
gem "sqlite3"
gem "puma"
gem "rails"

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "parallel_tests"
end

group :test do
  gem "capybara"
  gem "rspec"
  gem "rspec-rails"
  gem "parallel_rspec"
  gem "selenium-webdriver"
  gem 'simplecov', require: false
  gem "webdrivers"
end
