default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  adapter: mysql2
  host: mysql
  database: test<%= ENV['TEST_ENV_NUMBER'] %>
  username: user
  password: pass
production:
  <<: *default
  database: db/production.sqlite3
