name: rails_basic_ci
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RAILS_ENV: test
  SHOULD_PUBLISH_TEST_REPORTS: ${{ github.ref_name == github.event.repository.default_branch }}
  SHOULD_NOT_PUBLISH_TEST_REPORTS: ${{ github.ref_name != github.event.repository.default_branch }}
  TRUE: ${{ 1 == 1 }}
  FALSE: ${{ 1 == 0 }}

defaults:
  run:
    shell: bash

jobs:
  echo_env:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - run: |
          echo "SHOULD_PUBLISH_TEST_REPORTS=${SHOULD_PUBLISH_TEST_REPORTS}"
          echo "TRUE=${TRUE}"
          echo "FALSE=${FALSE}"
          echo "github.ref_name=${{github.ref_name}}"
          echo "github.event.repository.default_branch=${{github.event.repository.default_branch}}"
        shell: bash

  echo_env1:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - run: |
          echo echo_env1
        shell: bash

  echo_env2:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - run: |
          echo echo_env2
        shell: bash

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      actions: read
    strategy:
      fail-fast: false
      matrix:
        group_index: [0,1]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: rails/basics
      # nproc(=2)個のデータベースをセットアップする
      - run: bundle exec rails "parallel:setup[`nproc`]"
        working-directory: rails/basics
      - uses: dawidd6/action-download-artifact@v6
        with:
          name: test-result-*
          name_is_regexp: true
          path: ${{ runner.temp }}/default-branch-test-results
          branch: ${{ github.event.repository.default_branch }}
          workflow_conclusion: success
          if_no_artifact_found: warn
      - uses: r7kamura/split-tests-by-timings@v0
        id: split_tests
        with:
          reports: ${{ runner.temp }}/default-branch-test-results/**/test_results
          glob: spec/**/*_spec.rb
          index: ${{ strategy.job-index }}
          total: ${{ strategy.job-total }}
          working-directory: rails/basics
      - run: echo "$(seq -s, $((${{ matrix.group_index }} * $(nproc))) $((${{ strategy.job-index }} * $(nproc) + $(nproc) - 1)) | sed 's/,$//')"
      # インスタンス数×nproc(=2)個にテストグループを分割し、そのうち2グループ実行する
      - run: bundle exec parallel_rspec -n `nproc` ${{ steps.split_tests.outputs.paths }}
        working-directory: rails/basics
      - uses: actions/upload-artifact@v4
        if: ${{ success() || failure() }}
        with:
          name: test-result-${{ strategy.job-index }}
          path: |
            rails/basics/test_results/
            rails/basics/coverage/.resultset*.json
          include-hidden-files: true
          if-no-files-found: ignore
